spring:
  application:
    name: corona-import

  datasource:
    initialization-mode: always
    platform: postgres
    url: jdbc:postgresql://db:5432/corona
    username: postgres
    password: postgres
    
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: false

corona:
  data:
    import:
      path: ./downloads
      poller: 3600000
    download:
      # 1 hour
      poller: 3600000
        