server:
  port: 0

spring:
  application:
    name: corona-import

  datasource:
    initialization-mode: always
    platform: postgres
    url: jdbc:postgresql://localhost:5432/corona
    username: corona
    password: corona
    
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: false

logging:
  level:
    de.edgar: INFO
    org.hibernate.type: INFO

corona:
  data:
    import:
      path: /home/efurkert/Downloads
      poller: 5000
      daysToSum: 7
    download:
      poller: 60000
      connectTimeout: 5000
      readTimeout: 5000
      urls:
        - url: https://covid.ourworldindata.org/data/owid-covid-data.csv
          fileName: covid19-world
          header: iso_code,continent,location,date,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,new_deaths_smoothed,total_cases_per_million,new_cases_per_million,new_cases_smoothed_per_million,total_deaths_per_million,new_deaths_per_million,new_deaths_smoothed_per_million,reproduction_rate,icu_patients,icu_patients_per_million,hosp_patients,hosp_patients_per_million,weekly_icu_admissions,weekly_icu_admissions_per_million,weekly_hosp_admissions,weekly_hosp_admissions_per_million,new_tests,total_tests,total_tests_per_thousand,new_tests_per_thousand,new_tests_smoothed,new_tests_smoothed_per_thousand,positive_rate,tests_per_case,tests_units,total_vaccinations,total_vaccinations_per_hundred,stringency_index,population,population_density,median_age,aged_65_older,aged_70_older,gdp_per_capita,extreme_poverty,cardiovasc_death_rate,diabetes_prevalence,female_smokers,male_smokers,handwashing_facilities,hospital_beds_per_thousand,life_expectancy,human_development_index
          channel: worldChannel
        #  header: dateRep,year_week,cases_weekly,deaths_weekly,countriesAndTerritories,geoId,countryterritoryCode,popData2019,continentExp,notification_rate_per_100000_population_14-days
        #- url: https://opendata.ecdc.europa.eu/covid19/casedistribution/csv
        #  fileName: covid19-world
        #  header: dateRep,day,month,year,cases,deaths,countriesAndTerritories,geoId,countryterritoryCode,popData[0-9]{4},continentExp,Cumulative_number_for_14_days_of_COVID-19_cases_per_100000
        #  channel: worldChannel
        # org.apache.poi.ooxml.POIXMLException: Strict OOXML isn't currently supported, please see bug #57699
        #- url: https://www.ecdc.europa.eu/sites/default/files/documents/COVID-19-geographic-disbtribution-worldwide.xlsx
        #  fileName: covid19-world-xlsx
        #  header: dateRep,day,month,year,cases,deaths,countriesAndTerritories,geoId,countryterritoryCode,popData[0-9]{4},continentExp[.]*
        #  channel: worldChannel
        - url: https://covid19publicdata.blob.core.windows.net/rki/covid19-germany-federalstates.csv
          fileName: covid19-germany-federalstates
          header: id,Country/Region,federalstate,infections,deaths,date,newinfections,newdeaths
          channel: germanyChannel
        - url: https://covid19publicdata.blob.core.windows.net/rki/covid19-germany-counties.csv
          fileName: covid19-germany-counties
          header: id,Country/Region,county,countyname,type,federalstate,population,infections,deaths,shapearea,shapelength,date,newinfections,newdeaths,infectionrate,deathrate
          channel: germanyFederalStatesChannel
        - url: https://api.covid19tracking.narrativa.com/api
          fileName: covid19-world-api
          header: 
          channel: worldApiChannel
          afterChannel: 
            - worldChannel
            - germanyChannel
        - url: https://raw.githubusercontent.com/daenuprobst/covid19-cases-switzerland/master/covid19_cases_switzerland_openzh.csv
          fileName: covid19-switzerland-cases
          #header: Date,AG,AI,AR,BE,BL,BS,FR,GE,GL,GR,JU,LU,NE,NW,OW,SG,SH,SO,SZ,TG,TI,UR,VD,VS,ZG,ZH,CH,AG_diff,AG_pc,AG_diff_pc,AI_diff,AI_pc,AI_diff_pc,AR_diff,AR_pc,AR_diff_pc,BE_diff,BE_pc,BE_diff_pc,BL_diff,BL_pc,BL_diff_pc,BS_diff,BS_pc,BS_diff_pc,FR_diff,FR_pc,FR_diff_pc,GE_diff,GE_pc,GE_diff_pc,GL_diff,GL_pc,GL_diff_pc,GR_diff,GR_pc,GR_diff_pc,JU_diff,JU_pc,JU_diff_pc,LU_diff,LU_pc,LU_diff_pc,NE_diff,NE_pc,NE_diff_pc,NW_diff,NW_pc,NW_diff_pc,OW_diff,OW_pc,OW_diff_pc,SG_diff,SG_pc,SG_diff_pc,SH_diff,SH_pc,SH_diff_pc,SO_diff,SO_pc,SO_diff_pc,SZ_diff,SZ_pc,SZ_diff_pc,TG_diff,TG_pc,TG_diff_pc,TI_diff,TI_pc,TI_diff_pc,UR_diff,UR_pc,UR_diff_pc,VD_diff,VD_pc,VD_diff_pc,VS_diff,VS_pc,VS_diff_pc,ZG_diff,ZG_pc,ZG_diff_pc,ZH_diff,ZH_pc,ZH_diff_pc,CH_diff,CH_pc,CH_diff_pc
          header: Date,AG,AI,AR,BE,BL,BS,FR,GE,GL,GR,JU,LU,NE,NW,OW,SG,SH,SO,SZ,TG,TI,UR,VD,VS,ZG,ZH,CH,[\p{Print}]*
          channel: switzerlandCasesChannel
        - url: https://raw.githubusercontent.com/daenuprobst/covid19-cases-switzerland/master/covid19_fatalities_switzerland_openzh.csv
          fileName: covid19-switzerland-deaths
          #header: Date,AG,AI,AR,BE,BL,BS,FR,GE,GL,GR,JU,LU,NE,NW,OW,SG,SH,SO,SZ,TG,TI,UR,VD,VS,ZG,ZH,CH,AG_diff,AG_pc,AG_diff_pc,AI_diff,AI_pc,AI_diff_pc,AR_diff,AR_pc,AR_diff_pc,BE_diff,BE_pc,BE_diff_pc,BL_diff,BL_pc,BL_diff_pc,BS_diff,BS_pc,BS_diff_pc,FR_diff,FR_pc,FR_diff_pc,GE_diff,GE_pc,GE_diff_pc,GL_diff,GL_pc,GL_diff_pc,GR_diff,GR_pc,GR_diff_pc,JU_diff,JU_pc,JU_diff_pc,LU_diff,LU_pc,LU_diff_pc,NE_diff,NE_pc,NE_diff_pc,NW_diff,NW_pc,NW_diff_pc,OW_diff,OW_pc,OW_diff_pc,SG_diff,SG_pc,SG_diff_pc,SH_diff,SH_pc,SH_diff_pc,SO_diff,SO_pc,SO_diff_pc,SZ_diff,SZ_pc,SZ_diff_pc,TG_diff,TG_pc,TG_diff_pc,TI_diff,TI_pc,TI_diff_pc,UR_diff,UR_pc,UR_diff_pc,VD_diff,VD_pc,VD_diff_pc,VS_diff,VS_pc,VS_diff_pc,ZG_diff,ZG_pc,ZG_diff_pc,ZH_diff,ZH_pc,ZH_diff_pc,CH_diff,CH_pc,CH_diff_pc
          header: Date,AG,AI,AR,BE,BL,BS,FR,GE,GL,GR,JU,LU,NE,NW,OW,SG,SH,SO,SZ,TG,TI,UR,VD,VS,ZG,ZH,CH,[\p{Print}]*
          channel: switzerlandDeathsChannel
