spring:
  application:
    name: corona-web

  datasource:
    initialization-mode: always
    platform: postgres
    url: jdbc:postgresql://localhost:5432/corona
    username: corona
    password: corona
    
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: false

corona:
  data:
    daysToKum: 7
    daysToKumPop: 100000
    
logging:
  level:
    org:
      hibernate:
        type: INFO
